### ISSUE TITLE
Materialized view RelationType is view, so dbt tries to drop it each time and fails

### ISSUE THREAD

**Issue by kanomaxb** [DataEngineersNZ/dbt-snowflake-datops-materilizations#16]
Dbt 1.5.0

I am trying to use the materialized view materialization. 

The materialized view is created as expected. But on the second run dbt tries to drop it, and fails with error "SQL compilation error: Object found is of type 'MATERIALIZED_VIEW', not specified type 'VIEW'."

I guess this is because dbt uses SHOW TERSE OBJECTS IN SCHEMA to determine objects types, and according to doc https://docs.snowflake.com/en/sql-reference/sql/show-objects :

`For materialized views, this returns “VIEW”, not “MATERIALIZED VIEW”.`

**Comment by jonhopper-dataengineers** [comment]
Fixed on revision 0.2.7.6
